import Head from 'next/head'

import Navigation from '../components/Navigation'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Samuel Abu's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <h1 className='mt-20 text-center text-6xl font-bold'>Shalimar</h1>
    </div>
  )
}
